MyCatalog/Models/WishList.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyCatalog.Models
{
    public class WishList : BaseEntity
    {
        public virtual ICollection<WishListItem> WishListItems { get; set; }
        public WishList()
        {
            this.WishListItems = new List<WishListItem>();
        }
    }
}

MyCatalog/Controllers/WishListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MyCatalog.Models;

namespace MyCatalog.Controllers
{
    public class WishListController : Controller
    {
        IWishListService wishListService;

        public WishListController(IWishListService WishListService)
        {
            this.wishListService = WishListService;
        }


        public IActionResult Index()
        {
            var model = wishListService.GetWishListItems(this.HttpContext);
            
            return View(model);
        }

        public IActionResult AddToWishList(string Id)
        {
            wishListService.AddToWishList(this.HttpContext, Id);

            return RedirectToAction("Index");
        }

        public IActionResult RemoveFromWishList(string Id)
        {
            wishListService.RemoveFromWishList(this.HttpContext, Id);

            return RedirectToAction("Index");
        }


        //public PartialViewResult WishListSummary()
        //{
        //    var wishListSummary = wishListService.GetWishListSummary(this.HttpContext);

        //    return PartialView(wishListSummary);
        //}
    }
}

MyCatalog/Views/WishList/Index.cshtml
@model IEnumerable<MyCatalog.View_Model.WishListItemViewModel>

@{
    ViewData["Title"] = "My Wish List";
}

<h1>My Wish List</h1>


<table class="table">
    <thead>
        <tr>
            <th></th>
            <th>
                @Html.DisplayNameFor(model => model.ProductName)
            </th>
           
            <th>
                @Html.DisplayNameFor(model => model.Quanity)
            </th>

            
            <th></th>
        </tr>
    </thead>
    <tbody>
      
@foreach (var item in Model) {
    var photoPath = "~/Images/" + item.Image;
        <tr>

            <td>
                <img class="img-thumbnail" style="max-width: 80%; height: auto; width: auto\9;" src="@photoPath" asp-append-version="true" />
            </td>
            
            <td>
                @Html.DisplayFor(modelItem => "Iphone")
            </td>

            <td>
                @Html.HiddenFor(modelItem => item.Id)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Quanity)
            </td>

            <td>
            </td>
            <td>
                <a href ="@Url.Action("RemoveFromWishList", "WishList", new { id=item.Id })" class="btn btn-danger">Delete</a>
                @*@Html.ActionLink("Delete", "Delete", new { id=item.Id })*@
            </td>
        </tr>
}
    </tbody>
</table>